// app/disclaimer/page.tsx
import type { Metadata } from "next";
import LegalLayout from "../components/LegalLayout";
import { AlertTriangle, HardHat, BookOpen, ThumbsUp, Mail } from "lucide-react";

export const metadata: Metadata = {
  title: "Disclaimer | BitumenCalcPro",
  description:
    "Important disclaimer for BitumenCalcPro users. Understand the limitations of our bitumen calculator and when to consult a qualified engineer.",
  alternates: { canonical: "https://bitumencalcpro.com/disclaimer" },
  openGraph: {
    title: "Disclaimer | BitumenCalcPro",
    description:
      "Important disclaimer for BitumenCalcPro users. Understand when to consult a qualified engineer.",
    url: "https://bitumencalcpro.com/disclaimer",
    siteName: "BitumenCalcPro",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Disclaimer | BitumenCalcPro",
    description: "Important disclaimer for BitumenCalcPro users. Understand when to consult a qualified engineer.",
  },
};

const points = [
  {
    icon: AlertTriangle,
    color: "amber",
    title: "Results Are Estimates, Not Specifications",
    text: "The numbers BitumenCalcPro produces are mathematical estimates based on the inputs you provide and standard industry formulas. They are intended as a starting point — not as a final specification. Material quantities in real projects can vary based on site conditions, mix design specifics, compaction methods, waste factors, and dozens of other variables that an online calculator simply cannot account for.",
  },
  {
    icon: HardHat,
    color: "orange",
    title: "Always Verify with a Qualified Engineer",
    text: "We strongly recommend that any estimates generated by this tool be reviewed and verified by a licensed civil engineer or qualified pavement specialist before being used for procurement, budgeting, or construction purposes. The tool is designed to support professional judgment — not replace it.",
  },
  {
    icon: BookOpen,
    color: "blue",
    title: "No Professional Engineering Advice",
    text: "Nothing on BitumenCalcPro constitutes professional engineering, design, or construction advice. The tool applies general industry-standard formulas and typical density values which may not reflect your specific mix design, regional standards, or project requirements. Always consult relevant local codes, standards (e.g., AASHTO, BS, IS codes), and your mix design documentation.",
  },
  {
    icon: ThumbsUp,
    color: "violet",
    title: "Accuracy of Inputs Is Your Responsibility",
    text: "The quality of the output is entirely dependent on the accuracy of the inputs you provide. Garbage in, garbage out — as any engineer knows. Please double-check your project dimensions, mix type selection, and density values before relying on the results.",
  },
];

const colorClasses: Record<string, { icon: string; bg: string; border: string; iconBg: string }> = {
  amber: {
    icon: "text-amber-600",
    bg: "bg-amber-50",
    border: "border-amber-100",
    iconBg: "bg-amber-100 border-amber-200",
  },
  orange: {
    icon: "text-orange-600",
    bg: "bg-orange-50",
    border: "border-orange-100",
    iconBg: "bg-orange-100 border-orange-200",
  },
  blue: {
    icon: "text-blue-600",
    bg: "bg-blue-50",
    border: "border-blue-100",
    iconBg: "bg-blue-100 border-blue-200",
  },
  violet: {
    icon: "text-violet-600",
    bg: "bg-violet-50",
    border: "border-violet-100",
    iconBg: "bg-violet-100 border-violet-200",
  },
};

export default function DisclaimerPage() {
  return (
    <LegalLayout
      title="Disclaimer"
      subtitle="We're upfront about what our tool can and cannot do. Please read this before using our calculator for any project decision-making."
      lastUpdated="July 23, 2026"
      badge="Important Information"
      accentColor="orange"
    >
      {/* Alert Banner */}
      <div className="bg-amber-50 border-l-4 border-amber-400 rounded-r-2xl p-6 mb-10">
        <div className="flex items-start gap-4">
          <AlertTriangle size={24} className="text-amber-500 shrink-0 mt-0.5" />
          <div>
            <p className="font-bold text-amber-800 mb-1">Professional Review Required</p>
            <p className="text-amber-700 text-sm leading-relaxed m-0">
              This calculator is a decision-support tool. All outputs must be
              reviewed by a qualified engineer before being applied to any real
              construction project. Do not use these estimates as a substitute
              for professional engineering judgment.
            </p>
          </div>
        </div>
      </div>

      {/* Intro */}
      <p className="text-slate-600 text-base leading-relaxed mb-10">
        We built BitumenCalcPro to give civil engineers and paving contractors a
        fast, reliable starting point for their calculations. We take accuracy
        seriously — but we also believe in being completely transparent about
        what a web-based calculator can and cannot do. Please take a few minutes
        to read the following.
      </p>

      {/* Points */}
      <div className="space-y-6 mb-10">
        {points.map((point, idx) => {
          const Icon = point.icon;
          const colors = colorClasses[point.color];
          return (
            <div key={idx} className={`rounded-2xl border ${colors.border} ${colors.bg} p-7`}>
              <div className="flex items-start gap-4">
                <div className={`w-10 h-10 rounded-xl border flex items-center justify-center shrink-0 ${colors.iconBg}`}>
                  <Icon size={20} className={colors.icon} />
                </div>
                <div>
                  <h2 className="text-lg font-bold text-slate-900 mb-2">{point.title}</h2>
                  <p className="text-slate-600 text-sm leading-relaxed m-0">{point.text}</p>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Liability */}
      <div className="bg-slate-50 border border-slate-200 rounded-2xl p-7 mb-10">
        <h2 className="text-lg font-bold text-slate-900 mb-3">Limitation of Liability</h2>
        <p className="text-slate-600 text-sm leading-relaxed mb-4">
          BitumenCalcPro and its creators, contributors, and operators shall not
          be held liable for any errors, inaccuracies, or omissions in the
          calculator outputs, or for any damages — direct, indirect, incidental,
          or consequential — arising from the use of or reliance on this tool.
        </p>
        <p className="text-slate-600 text-sm leading-relaxed m-0">
          By using this calculator, you acknowledge that you understand its
          limitations and agree to use the results responsibly.
        </p>
      </div>

      {/* External Links */}
      <div className="bg-slate-50 border border-slate-200 rounded-2xl p-7 mb-10">
        <h2 className="text-lg font-bold text-slate-900 mb-3">External Links & References</h2>
        <p className="text-slate-600 text-sm leading-relaxed m-0">
          Our site may contain links to external websites for reference purposes.
          We do not control these websites and are not responsible for their
          content, accuracy, or privacy practices. Links do not constitute an
          endorsement.
        </p>
      </div>

      {/* CTA */}
      <div className="bg-gradient-to-br from-slate-900 via-slate-800 to-violet-950 rounded-2xl p-8 text-center">
        <Mail size={32} className="text-orange-400 mx-auto mb-3" />
        <h2 className="text-white font-bold text-xl mb-2">Found an Error in Our Calculations?</h2>
        <p className="text-slate-400 text-sm mb-5 max-w-md mx-auto">
          If you spot an inaccuracy or have feedback on our calculation
          methodology, please tell us. We take every report seriously.
        </p>
        <a
          href="/contact-us"
          className="inline-flex items-center gap-2 bg-orange-500 hover:bg-orange-400 active:scale-95 text-white px-6 py-3 rounded-full font-semibold text-sm transition-all shadow-md shadow-orange-900/40"
        >
          Report an Issue
        </a>
      </div>
    </LegalLayout>
  );
}
